connector.name=clickhouse
connection-url=jdbc:clickhouse:http://clickhouse:8123/lab4?compress=0&decompress=0
connection-user=admin
connection-password=xekg_eh9xyJDJFHJKSDHKqy_xa?rd!en66
clickhouse.map-string-as-varchar=true
