app.db.url=jdbc:postgresql://postgres:5432/postgres
app.db.username=postgres
app.db.password=postgres

app.hibernate.driver-class=org.postgresql.Driver
app.hibernate.hbm2ddl-auto=none
app.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
app.hibernate.show-sql=false
app.hibernate.format-sql=false
app.hibernate.current-session-context-class=thread
app.hibernate.physical-naming-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategySnakeCaseImpl

app.sink.batch-size=100

